[build-system]
requires = []
build-backend = "flit_core.buildapi"

[project]
name = "YDME 300NITAL PDK documentation"
authors = [{ name = "wushuang", email = "wushuang@latitudeda.com" }]
dynamic = ["version", "description"]
